---
- name: Configure Nginx webserver
  host: droplet group2
  become: true
  tasks:
   - name: Install Nginx server
     apt: 
       name: nginx
       state: latest
   -name: Start nginx server
    service: 
     name: nginx
     state: started